# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run modules JSON tests
        run: python test-modules-json.py

      - name: Verify if modules.json is changed
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files: $CHANGED_FILES"
          if [[ "$CHANGED_FILES" == *"modules.json"* ]]; then
            echo "Modules.json file changed."
            echo "modules_changed=true" >> $GITHUB_ENV
          else
            echo "No changes in the modules file."
            echo "modules_changed=false" >> $GITHUB_ENV
          fi

      - name: Run generation script
        if: env.modules_changed == 'true'
        run: python generate-readme.py

      - name: Check for changes
        if: env.modules_changed == 'true'
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Changes detected."
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "No changes detected."
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.modules_changed == 'true' && env.changes_detected == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README.md with latest module changes"
          git push origin dev